# ==============================================================================
# CHEQ RTI – VCL Snippet: error
# Type:     error
# Priority: 10
#
# Handles synthetic responses generated by the integration:
#   - 601  Serve the CAPTCHA challenge HTML page
#   - 603  Return a 301/302 redirect response
#   - 604  Return a 403 block response
#
# All other error codes fall through unmodified.
#
# Upload via Fastly CLI:
#   fastly vcl snippet create \
#     --service-id=<SERVICE_ID> --version=<VERSION> \
#     --name=cheq_rti_error --type=error --priority=10 \
#     --content=snippets/error.vcl
# ==============================================================================

call cheq_rti_synth;
