import { CloudFrontRequestEvent, CloudFrontRequestResult } from 'aws-lambda';
import { config } from './config';
import { RTILoggerService } from "../../core/services/rti-logger.service";
import { RTIService } from "../../core/services/rti.service";
import { RTIHelperService } from "../../core/services/rti-helper.service";
import { name, version } from "../package.json";
import { RequestHeaders, RTIRequest } from "../../core/models/rti-request.model";
import { CloudFrontHeaders, CloudFrontRequest } from 'aws-lambda/common/cloudfront';
import { Action } from '../../core/models/action.model';
import { ActionStrategy } from '../../core/models/action-strategy.model';
import { RTIResponse } from '../../core/models/rti-response.model';
import { generateDefaultBlockPage } from '../../core/helpers/block-page-helpers';

export enum RequestType {
  VIEWER_REQUEST,
  ORIGIN_REQUEST,
}

const logger = new RTILoggerService(`${name}-${version}`, config);
const rtiHelperService = new RTIHelperService(config);
const rtiService = new RTIService(config);

export const handle = async (event: CloudFrontRequestEvent, requestType: RequestType): Promise<CloudFrontRequestResult> => {
    //debugger; // Pause for breakpoints when using SAM - remove for production
    const isDebugEnabled = config.debug;

    if (isDebugEnabled) {
        // event.Records?.[0]?.cf?.config?.requestId is the unique request id generated by CloudFront for each request 
        // and can be used for tracking\debugging (The x-amz-cf-id header in the request represents this id).
        const requestTypeStr = requestType === RequestType.VIEWER_REQUEST ? "Viewer" : requestType === RequestType.ORIGIN_REQUEST ? "Origin" : "Unknown";
        console.log(`Original CF Event (${requestTypeStr} Request Flow): ${JSON.stringify(event)}`);
    }

    // Safe: CloudFront always provides exactly one record with this structure when invoking Lambda@Edge.
    // Would only throw if invoked directly (not via CloudFront), which should not happen in production.
    const cfRequest : CloudFrontRequest = event.Records[0].cf.request;

    try {
        // Filter out ignored paths and already validated challenges and validate challenge if exists
        const requestURL = getRequestUrl(cfRequest);

        if (rtiHelperService.shouldIgnore(requestURL.pathname) || await isValidChallenge(cfRequest, isDebugEnabled)) {
            return cfRequest;
        }

        // Build RTI request payload
        const startRTI = Date.now();

        const fetchedHeaders = getHeaders(config.keepHeadersNames, cfRequest.headers);
        const cookieHeaderMap = (cfRequest.headers["cookie"]?.map((kv) => kv.value).join(', ') || "").split(";").map(c => c.trim());
        let payload: RTIRequest = {
            tagHash: config.tagHash,
            apiKey: config.apiKey,
            // isHeaderNamesOrdered is unknown so kept empty
            channel: "cloudfront-cdn-integration",
            customId1: rtiHelperService.getEventType(requestURL.pathname, cfRequest.method),
            endUserParams: {
                clientIp: cfRequest.clientIp,
                requestUrl: requestURL.href,
                headerNames: Object.keys(fetchedHeaders).filter(x => fetchedHeaders[x]).join(","),
                method: cfRequest.method,
                headers: fetchedHeaders,
            },
            duidCookie: cookieHeaderMap.find(c => c.startsWith("_cq_duid="))?.split("=")[1], // Relevant for API version 4.0 and above
            pvidCookie: cookieHeaderMap.find(c => c.startsWith("_cq_pvid="))?.split("=")[1], // Relevant for API version 4.0 and above
            sCookie: cookieHeaderMap.find(c => c.startsWith("_cq_s="))?.split("=")[1] // Relevant for API version 4.1 and above
        };

        // Add JA3 and JA4 fingerprints if available. 
        // These headers are injected by CloudFront at the viewer request stage, 
        // so they will only be available in origin request stage and not in viewer request stage.
        
        // @ts-ignore: This specific line is known to be safe
        payload.endUserParams.headers.cheq_ja3 = cfRequest.headers["cloudfront-viewer-ja3-fingerprint"]?.map((kv) => kv.value).join(', ');
        // @ts-ignore: This specific line is known to be safe
        payload.endUserParams.headers.cheq_ja4 = cfRequest.headers["cloudfront-viewer-ja4-fingerprint"]?.map((kv) => kv.value).join(', ');

        if (isDebugEnabled) {
            console.log(`RTI Request payload: ${JSON.stringify(payload)}`);
        }

        // Call RTI service
        const rtiResponse = await rtiService.callRTI(payload);

        if (isDebugEnabled) {
            console.log(`RTI Response: ${JSON.stringify(rtiResponse)}`);
        }

        if (config.telemetry) {
            await logger.info(`rti_duration: ${Date.now() - startRTI}`);
        }

        // Get action from RTI response and handle accordingly
        const action = rtiHelperService.getAction(rtiResponse);

        if (isDebugEnabled) {
            const actionName = Action[action];
            console.log(`action upon response: ${actionName ? `${actionName} (${action})` : action}`);
        }

        // If action is not allow, return the corresponding response to client based on action strategy
        if (action !== Action.ALLOW) {
            const actionStrategy = rtiHelperService.getActionStrategy(action);

            if (isDebugEnabled) {
                console.log(`action strategy: ${actionStrategy !== null ? `${ActionStrategy[actionStrategy]} (${actionStrategy})` : "none (should not happen)"} `);
            }

            switch (actionStrategy) {
                case ActionStrategy.ACCESS_DENIED:
                    return {
                        status: '403',
                        headers: { 'content-type': [{ key: 'Content-Type', value: 'text/html;charset=UTF-8' }] },
                        body: generateDefaultBlockPage('403', 'Access Denied', rtiResponse.ids.rayId, getCfRequestId(event)),
                    };
                case ActionStrategy.NOT_FOUND:
                    return {
                        status: '404',
                        headers: { 'content-type': [{ key: 'Content-Type', value: 'text/html;charset=UTF-8' }] },
                        body: generateDefaultBlockPage('404', 'Not Found', rtiResponse.ids.rayId, getCfRequestId(event)),
                    };
                case ActionStrategy.REDIRECT:
                    const headers: CloudFrontHeaders = {
                        'x-cheq-cf-request-id': [{ key: 'x-cheq-cf-request-id', value: getCfRequestId(event) }],
                        'x-cheq-id': [{ key: 'x-cheq-id', value: rtiResponse.ids.rayId }],
                        location: [{ key: 'Location', value: config.redirectLocation || "https://www.cheq.ai/" }],
                    };
                    return {
                        status: '302',
                        headers,
                    };
                case ActionStrategy.CAPTCHA:
                    try {
                        if (config.challenge) {
                            const challengeResult = await config.challenge(cfRequest, rtiResponse);
                            return challengeResult;
                        }
                        break;
                    } catch (e) {
                        const err: Error = e as Error;
                        const cfRequestId = getCfRequestId(event);
                        console.error(`Challenge error handling request '${cfRequestId}':`, err);
                        await logger.error(`Challenge error handling request '${cfRequestId}': ${err.message}`);
                        return cfRequest;
                    }
                default:
                    break;
            }
        }

        // action is Action.ALLOW, pass headers
        setHeaders(cfRequest.headers, rtiResponse);

        return cfRequest;
    } catch (e) {
        const err: Error = e as Error;
        const cfRequestId = getCfRequestId(event);
        console.error(`Error handling request '${cfRequestId}':`, err);
        await logger.error(`Error handling request '${cfRequestId}': ${err.message}`);
    }

    return cfRequest;
};

async function isValidChallenge(cfRequest : CloudFrontRequest, isDebugEnabled: boolean | undefined): Promise<boolean> {
    const validChallenge = await config.validateChallenge?.(cfRequest, isDebugEnabled) ?? false;
    return validChallenge;
}

function getRequestUrl(cfRequest : CloudFrontRequest): URL {
    const host = (cfRequest.headers["host"]?.map((kv) => kv.value) || "").join(', ');

    let url = `https://${host}${cfRequest.uri}`;

    if (cfRequest.querystring) {
        url += `?${cfRequest.querystring}`;
    }

    return new URL(url);
}

function setHeaders(headers: CloudFrontHeaders, rtiResponse: RTIResponse) {
    // Add RTI result header to the request that will be sent to the origin. 
    // This can be used by the origin for debugging, logging, or making decisions based on the RTI result.
    // Note: The only way to see this header in the browser is to have the origin echo it back in the response headers, so basically we will never see this header in the browser, only in CloudWatch.

    const result = [
        `version=${rtiResponse.metadata.version}`,
        `verdict=${rtiResponse.decision.verdict}`,
        `threat-type-code=${rtiResponse.classification.code}`,
        `ids=${JSON.stringify(rtiResponse.ids)}`,
        `reasons=${rtiResponse.cheqDetection.reasons.join(',')}`,
    ].join(";");

    headers["x-cheq-rti-result"] = [{ key: 'x-cheq-rti-result', value: result }];
}

function getHeaders(keepHeadersNames: string[], headers: CloudFrontHeaders): RequestHeaders {
    const result: RequestHeaders = {};
    const headerKeys = keepHeadersNames && keepHeadersNames.length > 0 ? keepHeadersNames : Object.keys(headers);
    
    for (const headerName of headerKeys) {
        const headerValues = headers[headerName];
        if (headerValues) {
            result[headerName] = headerValues.map((kv) => kv.value).join(', ');
        }
    }
    
    return result;
}

function getCfRequestId(event: CloudFrontRequestEvent): string {
    try {
        // This id is represented by CloudFront as x-amz-cf-id header in the request and can  be used for tracking\debugging.
        const cfRequestId = event.Records?.[0]?.cf?.config?.requestId ?? "unknown_request_id";
        return cfRequestId;
    } catch (e) {
        const err: Error = e as Error;
        return `on_error_request_id (${err.message})`;
    }
}
